<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.eia</groupId>
    <artifactId>extract-insight-action</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>extract-insight-action</name>

    <modules>
        <module>java-core</module>
        <module>multiagent</module>
        <module>agent-service</module>
        <module>extract/functions/mailbox-to-queue</module>
        <module>extract/functions/queue-to-db</module>
        <module>extract/functions/cu-queue-to-db</module>
        <module>insight/ui</module>
    </modules>
</project>